name: Build-Push-Backend-To-Do-App

on:
  # # using this to trigger the workflow from another workflow build.yaml but that's not working no-idea why? later check and fix
  # workflow_call:
  #   inputs:
  #     username:
  #       required: true
  #       type: string
  #     password:
  #       required: true
  #       type: string
  push:
    branches:
      - main
    paths:
      - 'application-code/to-do-app/backend/**'
  workflow_dispatch:

env:
  working_dir: 'application-code/to-do-app/backend/'

jobs:
  build:
    name: To-Do-Backend-Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working_dir }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    

      - name: Get version tag
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "VERSION=${VERSION}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          IMAGE_NAME=abhiverma001/backend-to-do-app
          IMAGE_TAG=${{ env.VERSION }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: |
          IMAGE_NAME=abhiverma001/backend-to-do-app
          IMAGE_TAG=${{ env.VERSION }}
          docker push $IMAGE_NAME:$IMAGE_TAG

      # Step 6: Optionally, push the `latest` tag (optional step) uncomment if you want to show latest image as latest tag
      # - name: Push latest tag (optional)
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     IMAGE_NAME=abhiverma001/backend-to-do-app
      #     docker tag $IMAGE_NAME:${{ env.VERSION }} $IMAGE_NAME:latest
      #     docker push $IMAGE_NAME:latest