name: Build

on:
  workflow_run:
    workflows:
      - semver-tag-release.yml  # Wait for this workflow to complete
    status:
      - success

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secrets
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}"
 
  # frontend-to-do-app:
  #   name: Frontend To-Do App Build
  #   uses: ./.github/workflows/frontend-to-do-build.yml
  #   with:
  #     username: ${{ secrets.DOCKER_USERNAME }}
  #     password: ${{ secrets.DOCKER_PASSWORD }}    

  # backend-to-do-app:
  #   name: Backend To-Do App Build
  #   uses: ./.github/workflows/backend-to-do-build.yml
  #   with:
  #     username: ${{ secrets.DOCKER_USERNAME }}
  #     password: ${{ secrets.DOCKER_PASSWORD }}
