name: Build

on:
  workflow_run:
    workflows:
      - semver-tag-release.yml  # Wait for this workflow to complete
    status:
      - success

  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  frontend-to-do-app:
    name: Frontend To-Do App Build
    uses: ./.github/workflows/frontend-to-do-build.yml
    with:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}    

  backend-to-do-app:
    name: Backend To-Do App Build
    uses: ./.github/workflows/backend-to-do-build.yml
    with:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}    
