name: Build-Push-Frontend-To-Do-App

on:
  workflow_run:
    workflows:
      - semver-tag-release.yml  # Wait for this workflow to complete
    status:
      - success

  push:
    branches:
      - main
    paths:
      - 'application-code/frontend/**'  # Trigger only on changes in this folder

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch the entire history including tags

      # Step 2: Check if changes were made in the application-code/frontend/** path
      - name: Check for changes in To-Do frontend app path
        id: check-changes
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files: $CHANGED_FILES"
          if ! echo "$CHANGED_FILES" | grep -q '^application-code/frontend/'; then
            echo "No changes detected in application-code/frontend/**. Skipping workflow."
            exit 0
          fi

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Get the version tag (latest tag from Git)
      - name: Get version tag
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "VERSION=${VERSION}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=abhiverma001/fronend-to-do-app
          IMAGE_TAG=${{ env.VERSION }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG -f application-code/frontend/Dockerfile .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          IMAGE_NAME=abhiverma001/fronend-to-do-app
          IMAGE_TAG=${{ env.VERSION }}
          docker push $IMAGE_NAME:$IMAGE_TAG

      # Step 6: Optionally, push the `latest` tag (optional step) uncomment if you want to show latest image as latest tag
      # - name: Push latest tag (optional)
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     IMAGE_NAME=abhiverma001/fronend-to-do-app
      #     docker tag $IMAGE_NAME:${{ env.VERSION }} $IMAGE_NAME:latest
      #     docker push $IMAGE_NAME:latest

