name: Build-Push-Frontend-To-Do-App

on:
  # # using this to trigger the workflow from another workflow build.yaml but that's not working no-idea why? later check and fix
  # workflow_call:
  #   inputs:
  #     username:
  #       required: true
  #       type: string
  #     password:
  #       required: true
  #       type: string
  push:
    branches:
      - main
    paths:
      - 'application-code/to-do-app/frontend/**'

  pull_request:
    paths:
      - 'application-code/to-do-app/frontend/**'

  workflow_dispatch:

env:
  working_dir: 'application-code/to-do-app/frontend/'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working_dir }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    

      - name: Get version tag
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          
          # If running on main, use only version as tag
          if [[ "$BRANCH_NAME" == "main" ]]; then
            IMAGE_TAG=$VERSION
          else
            # Remove slashes from branch name and append to version
            CLEAN_BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's|/|-|g')
            IMAGE_TAG="${VERSION}-${CLEAN_BRANCH_NAME}"
          fi
          
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "Using tag: ${IMAGE_TAG}"

      - name: Build Docker image
        run: |
          IMAGE_NAME=abhiverma001/frontend-to-do-app
          docker build -t $IMAGE_NAME:${{ env.IMAGE_TAG }} .

      - name: Push Docker image
        run: |
          IMAGE_NAME=abhiverma001/frontend-to-do-app
          docker push $IMAGE_NAME:${{ env.IMAGE_TAG }}
          
      # Step 6: Optionally, push the `latest` tag (optional step) uncomment if you want to show latest image as latest tag
      # - name: Push latest tag (optional)
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     IMAGE_NAME=abhiverma001/frontend-to-do-app
      #     docker tag $IMAGE_NAME:${{ env.VERSION }} $IMAGE_NAME:latest
      #     docker push $IMAGE_NAME:latest